/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package snake;

import java.awt.event.KeyEvent;

/**
 *
 * @author nezharen
 */
//The size of ground is 23(0~22)* 23(0~22)
//The avalible ground is 21(1~21) * 21(1~21)

public class SnakeGame extends javax.swing.JFrame {

    /**
     * Creates new form SnakeGame
     */
    public SnakeGame() {
        for (int i = 0; i < 23; i++)
            for (int j = 0; j < 23; j++)
                map[i][j] = false;
        ground = new Ground(map);
        snake = new Snake(map);
        food = new Food(map);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMap = new MapPanel(ground, snake, food);
        jStart = new javax.swing.JButton();
        jStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("贪吃蛇");
        setName("SnakeGame"); // NOI18N
        setResizable(false);

        jMap.setBorder(null);
        jMap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMapKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jMapLayout = new javax.swing.GroupLayout(jMap);
        jMap.setLayout(jMapLayout);
        jMapLayout.setHorizontalGroup(
            jMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        jMapLayout.setVerticalGroup(
            jMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jStart.setText("开始游戏");
        jStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartActionPerformed(evt);
            }
        });

        jStop.setText("结束游戏");
        jStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jStart)
                    .addComponent(jStop))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(331, Short.MAX_VALUE)
                .addComponent(jStart)
                .addGap(27, 27, 27)
                .addComponent(jStop)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartActionPerformed
        // TODO add your handling code here:
        
        jMap.setFocusable(true);
        jStart.setFocusable(false);
        jStop.setFocusable(false);
        jStart.setEnabled(false);
        GameThread t = new GameThread(map, snake, food, jMap);
        t.start();
    }//GEN-LAST:event_jStartActionPerformed

    private void jStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStopActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jStopActionPerformed

    private void jMapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMapKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                snake.setDirection(Snake.UP_DIRECTION);
                break;
            case KeyEvent.VK_DOWN:
                snake.setDirection(Snake.DOWN_DIRECTION);
                break;
            case KeyEvent.VK_LEFT:
                snake.setDirection(Snake.LEFT_DIRECTION);
                break;
            case KeyEvent.VK_RIGHT:
                snake.setDirection(Snake.RIGHT_DIRECTION);
                break;
        }
    }//GEN-LAST:event_jMapKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnakeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnakeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnakeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnakeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnakeGame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jMap;
    private javax.swing.JButton jStart;
    private javax.swing.JButton jStop;
    // End of variables declaration//GEN-END:variables
    
    //map[i][j] is true when point(i,j) is ground or snake body.
    private boolean map[][] = new boolean[23][23];
    private Ground ground;
    private Snake snake;
    private Food food;
}
